### ISSUE TITLE
Update Docs

### ISSUE THREAD

**Issue by Yoda3D** [GrannyCookies/scratchext2#1]
Update http://stefanbates.com/scratchext2/help/loader/ to show all four libraries, as opposed to the two.

**Comment by bates64** [comment]
Will add. We've moved over to github pages, by the way.

**Comment by bates64** [comment]
Added. Can you add the extra blocks to the gh-pages branch for me, Yoda?

**Comment by Yoda3D** [comment]
Um, how do I find the branches?

**Comment by bates64** [comment]
At the main root of scratchext2, click branch: master, and select gh-pages.
https://github.com/GrannyCookies/scratchext2/tree/gh-pages
