### ISSUE TITLE
I can't start scratchext2

### ISSUE THREAD

**Issue by ghost** [GrannyCookies/scratchext2#10]
There is now button on the left anymore ?!

How can I start now ScratchExt 2?

**Comment by ghost** [comment]
I noticed that too! What is going on!?

**Comment by ghost** [comment]
@easyscratcher I think you have to share it for the blocks to be available.

**Comment by ghost** [comment]
That is not my job. I only make the webpages.

**Comment by Felizolinha** [comment]
You can still load it through the project page button, the css for the buttons aren't loading because of the new proxy (I'm waiting for @GrannyCookies  to fix it), see this issue for more details: #9

**Comment by ghost** [comment]
It isn't working when I want to load it throgh the project page button :/

**Comment by Felizolinha** [comment]
@easyscratcher could you tell me if there are any errors being thrown into the console?

**Comment by ghost** [comment]
@Felizolinha  yes.. wait

**Comment by ghost** [comment]
@Felizolinha yes, there is an error: <code>Failed to load resource: net::ERR_BLOCKED_BY_CLIENT</code>

**Comment by Felizolinha** [comment]
@easyscratcher Is it the only error it's showing to you? I don't think it's coming from ScratchExt. From what file is it coming from according to the console?

**Comment by bates64** [comment]
@easyscratcher Are you using adblock?

**Comment by ghost** [comment]
yes...

**Comment by ghost** [comment]
why?

**Comment by Felizolinha** [comment]
@easyscratcher AdBlock usually is the one to give these errors, but they aren't supposed to interfere with ScratchExt.

**Comment by ghost** [comment]
oh ok

**Comment by ghost** [comment]
What is this?!
![2015-02-12 18_51_41-welcome auf scratch](https://cloud.githubusercontent.com/assets/10178784/6173458/837add66-b2e8-11e4-8c86-a4fcbb7fe542.png)

**Comment by ghost** [comment]
It's the scratchext button coming through the editor, I have the same problem, until you click it.

**Comment by ghost** [comment]
Oh.. Lol

**Comment by ghost** [comment]
I thought I was talking about that big a while ago and they said it would be too hard.

**Comment by bates64** [comment]
yeah
it would be impossible

**Comment by ghost** [comment]
@GrannyCookies Could you make a console.log version of Narrative? I have no idea what it means :/
