### ISSUE TITLE
Suggestion - Remove red ScratchExt background?

### ISSUE THREAD

**Issue by MeridiumDevelopment** [GrannyCookies/scratchext2#14]
I have GrannyCookies snazzy epic navbar repaint. Thingy I found on the chrome web store, the Red background on the ScratchExt kinda disturbs me a bit. Distracts me - but if you want to keep please do.
![scratchext](https://cloud.githubusercontent.com/assets/10271160/6335438/7b1ee348-bb93-11e4-8301-0bb80ec6ec8b.png)

**Comment by MeridiumDevelopment** [comment]
Locking suggestion

**Comment by bates64** [comment]
That doesn't even work for scratchext 2.0 anymore anyway :P
