### ISSUE TITLE
Multi-Click to run.

### ISSUE THREAD

**Issue by MeridiumDevelopment** [GrannyCookies/scratchext2#15]
In the editor when I attempt to press the Red ScratchExt button to activate the blocks it takes multiple clicks to activate. Sometimes it won't even activate at all.

**Comment by Felizolinha** [comment]
This issue is not related to ScratchExt 2.0, can someone close it?

**Comment by ghost** [comment]
The Button is only working for ScratchExt 1.0 I think

**Comment by bates64** [comment]
I will be working on a chrome extension for ScratchExt 2.0 shortly.

**Comment by MeridiumDevelopment** [comment]
@GrannyCookies You have made a extension. I got it - also can you add it was made by DerpyFanta or golden-scratch aswell

**Comment by bates64** [comment]
@DerpyFanta Where?

**Comment by MeridiumDevelopment** [comment]
search scratchext on the web store.

**Comment by bates64** [comment]
Oh, that one is old. :P
