### ISSUE TITLE
Install now loads automattically.

### ISSUE THREAD

**Issue by bates64** [GrannyCookies/scratchext2#16]
Also there are new labels, such as "testing needed".

**Comment by Felizolinha** [comment]
You're a genious! This approach is incredibly smart! I'm testing some stuff to make it more compatible with other extensions in case they use this method (I'll implement it in TGB's Extension :p)

The only loading error I've stumbled upon until now is probably server-related (but it doesn't happen in every project, I have no idea why).
Error:
`XMLHttpRequest cannot load http://scratchextproxy.x10.mx/?p=load-btn.js&c=1424817911828&_=1424817911829. Request header field X-Requested-With is not allowed by Access-Control-Allow-Headers.`

**Comment by bates64** [comment]
That's weird, it should set the header. It's server related though :)
So it works? :D

**Comment by ghost** [comment]
Yes, great :)

**Comment by bates64** [comment]
@easyscratcher Yay!

**Comment by Felizolinha** [comment]
Found a glitch: This method does not load the extension when using "Create" to make a new project until the user clicks "See the project page" or reloads it. A workaround for that would be redefining JSredirectTo to load ScratchExt when the url ends in "projects/editor".

**Comment by bates64** [comment]
I'll add this as an issue @Felizolinha.
