### ISSUE TITLE
2.0 Online Editor Glitch

### ISSUE THREAD

**Issue by MeridiumDevelopment** [GrannyCookies/scratchext2#20]
Just found a glitch in the 2.0 Editor. I am running both the Chrome Extension and the Tampermonkey Userscript.
![editor2 0 glitch](https://cloud.githubusercontent.com/assets/10271160/6541778/296cd52c-c4db-11e4-906c-73cdcb7cb792.png)
AbScratchExt?!

**Comment by GrannyCookies** [comment]
That is a ScratchExt 1.0 error.
