### ISSUE TITLE
When you switch to costumes, you can see ScratchExt on the side.

### ISSUE THREAD

**Issue by ghost** [GrannyCookies/scratchext2#6]
I'm being a bit picky, but anything to make ScratchExt better. :)

**Comment by bates64** [comment]
It'll be really difficult to fix.

**Comment by Felizolinha** [comment]
The only way to fix this would be to grab the color of a pixel like the [ColorZilla](http://www.colorzilla.com/) extension does with it's eyedropper functionality, but I have no idea on how it does it. There is also one other way to do it that I'm pretty sure is impossible, if we could find a way to let the click go through a div (like pointer-events:none does) but still grab the click event, we could know if the costumes button was clicked.

**Comment by ghost** [comment]
Agreed. Nevermind.
