### ISSUE TITLE
cdn.rawgit.com pernamently caches files :/

### ISSUE THREAD

**Issue by bates64** [GrannyCookies/scratchext2#7]
Using rawgit's CDN won't work for ScratchExt, we need to find another way.
(I can always use stefanbates.com as a fallback, but I don't want that tbh)

Any ideas?

**Comment by ghost** [comment]
oh.. that's not good :(

**Comment by Felizolinha** [comment]
We could use github.io, just create a ScratchExt organization and clone this repository with it's name changed to (organization name).github.io, it updates files in 5 minutes :p
If you want, I can create the organization :)

**Comment by bates64** [comment]
Or, this weekend, I can copy the code for rawgit (from it's repo) and put it onto my Pi. What do you think?
It's Node.js btw.

**Comment by bates64** [comment]
For now we can use stefanbates.com. I'll implement it now

**Comment by Felizolinha** [comment]
I thought about that, but you have to make sure it only has access to files from this repository :p

**Comment by bates64** [comment]
What do you mean?

**Comment by Felizolinha** [comment]
Because people could find out about it and use it as an alternative rawgit :S Specially as we need blacklisting disabled (at least for our repo). Your bank account will thank you for blocking other repos ;)

**Comment by bates64** [comment]
Yeah, lol. I've implemented the stefanbates.com system (which is just a direct copy of the repo). I will implement blacklisting on the pi, don't worry.

**Comment by bates64** [comment]
Scratch that, I've made a php proxy thingy, just do the normal scratchext.root + 'path/to/file.js'.

For example:
http://scratchextproxy.x10.mx/?q=start.js
