### ISSUE TITLE
Backwards-compatibility with ScratchExt 1.0

### ISSUE THREAD

**Issue by bates64** [GrannyCookies/scratchext2#8]
Suggested by MrSherlockHolmes.

We should add the install library as a scratchext 2.0 library which would install scratchext 1.0 stuff, allowing for backwards-compatibilty. What do you think?

**Comment by ghost** [comment]
Yep, thanks GrannyCookies! ScratchExt 1 has loads of blocks and most projects using ScratchExt use it. Plus it would feel more like an update, rather than a change of extension. Just a question, however, would it require just get script or would you need to add all the scripting from ScratchExt 1?

**Comment by Felizolinha** [comment]
Adding a library that installed the old install library (o_o) would need everyone to update their codes to install the old install library. It would be better to support the old install blocks natively or have a way to detect if it uses the ScratchExt 1 and then automatically install the old library.

**Comment by bates64** [comment]
If we added a library that installed called "Loader" (like ScratchExt 1.0), even without defining block names we should be able to run blocks that don't actually exist :P Can somebody experiment, while I add a settings page?

**Comment by bates64** [comment]
@MrSherlockHolmes It would just require getScript.

**Comment by ghost** [comment]
If it only required getScript, it might be a good idea.

**Comment by bates64** [comment]
@MrSherlockHolmes Problem is, we need to detect ScratchExt 1.0 and install the libraries from that.

**Comment by Felizolinha** [comment]
Oh, we can use the project's JSON to detect it, not sure if it's the most optimized way to do it though.

**Comment by ghost** [comment]
Can we not just ask scratchext users to use a new command like in scratchext2 where in notes and credits you put ScratchExt=Speech; ?

**Comment by Felizolinha** [comment]
We really shouldn't trust users to do an action to make it compatible with the new version, it's just not reliable.

**Comment by ghost** [comment]
That's true, in that case, what could we try?

**Comment by bates64** [comment]
@Felizolinha Agreed.
(Concerning the JSON) I wrote a command to get project JSON, use scratchext.getProjectJSON(url).

**Comment by ghost** [comment]
So what url would you type for https://raw.githubusercontent.com/MrSherlockHolmes/NarrativeC/master/DataNarrative ?

**Comment by Felizolinha** [comment]
@GrannyCookies I know, that's where I got the idea from :p

**Comment by bates64** [comment]
Oh, lol.
@MrSherlockHolmes You need to rename the file to DataNarrative.js, by the way.

**Comment by ghost** [comment]
@GrannyCookies Ok

**Comment by bates64** [comment]
So, I did a run on http://scratch.mit.edu/projects/33544392/, and I've found a way.
We need to look for, in the JSON, in the "scripts" section, inside 1, 2, 3, 4 etc, "– Import –.installedHat"

**Comment by bates64** [comment]
Actually, that only looks in the Stage :(

**Comment by bates64** [comment]
Oh, I have an idea! An "install scratchext 1.0" button :P

**Comment by Felizolinha** [comment]
@GrannyCookies It would be better if it detected ScratchExt 1 automatically :p

**Comment by bates64** [comment]
I know, but it can't :P

**Comment by ghost** [comment]
@GrannyCookies I agree. Automatic detecting is so hard :P

**Comment by bates64** [comment]
@all Hey, I've made a settings page for ScratchExt which we can put stuff in! Click your name (where the dropdown nav is) and select "ScratchExt Settings". What should I put there?

**Comment by bates64** [comment]
:D

**Comment by Felizolinha** [comment]
After detecting ScratchExt 1, should it also allow the user to use ScratchExt 2?

**Comment by bates64** [comment]
Yes. If you can.

**Comment by bates64** [comment]
Try and notify the user that they should use 2 though.

**Comment by Felizolinha** [comment]
@GrannyCookies Do you remember which day was ScratchExt 2.0 released(if it's not just a beta as of now xD)?

**Comment by bates64** [comment]
Nope

**Comment by Felizolinha** [comment]
Nvm, it's not necessary :p

**Comment by Felizolinha** [comment]
Backwards compatibility added with [commit 5893256918ce0a38688c8d9ca61113ee78bc2305](https://github.com/GrannyCookies/scratchext2/commit/5893256918ce0a38688c8d9ca61113ee78bc2305). Any ideas on how to make it better? It surely could be improved by deeply searching the JSON for blocks that use the "- Import -" library.

**Comment by ghost** [comment]
I really like the new button at the top. By the way,  why can't I access it when I'm in the editor? It's not required since I have an edited bookmark, but just wondering.

**Comment by Felizolinha** [comment]
@MrSherlockHolmes see #9. Also, which button you're talking about?

**Comment by bates64** [comment]
@Felizolinha @MrSherlockHolmes There is no "install scratchext 1.0" button in the editor currently.

**Comment by Felizolinha** [comment]
With the "Install ScratchExt 1.0" button that has been added since then, this issue has been mostly solved.
