### ISSUE TITLE
Proxy is providing CSS files with wrong MIME type

### ISSUE THREAD

**Issue by Felizolinha** [GrannyCookies/scratchext2#9]
The CSS files are being provided with a MIME type of text/javascript instead of text/css.
Example error:
`Resource interpreted as Stylesheet but transferred with MIME type text/javascript:
"http://scratchextproxy.x10.mx/?p=/css/scratchext-editor-btn.css"`

**Comment by bates64** [comment]
Oh, haha.
Okay.

**Comment by bates64** [comment]
Ok, the new syntax for the proxy is:
http://scratchextproxy.x10.mx/?p=start.js&mime=text/javascript

Basically just specify the MIME type.

**Comment by Felizolinha** [comment]
@GrannyCookies thanks for the "fix" :D

**Comment by bates64** [comment]
:P

**Comment by ghost** [comment]
@all well done you two!
